### ISSUE TITLE
"Bot requires code grant"

### ISSUE THREAD

**Issue by swaree** [Euophrys/mahjong-discord-bot#24]
Just before finishing the invite process, an error pops out as the title of this issue. From [discord.js's guide](https://discordjs.guide/preparations/adding-your-bot-to-servers.html#bot-invite-links): 

> _If you get an error message saying "Bot requires a code grant", then head over into your application's settings and disable the "Require OAuth2 Code Grant" option._

**Comment by Euophrys** [comment]
I disabled it, I don't think she needs it?

**Comment by swaree** [comment]
> I disabled it, I don't think she needs it?

I don't know for sure but disabling that option worked; thanks for answering! Take care.
